server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/address_db?allowPublicKeyRetrieval=true&useSSL=false}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      initialization-fail-timeout: 0
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

app:
  yandex:
    api-key: ${YANDEX_API_KEY:test_key}
    url: https://geocode-maps.yandex.ru/1.x
  dadata:
    api-key: ${DADATA_API_KEY:test_key}
    secret-key: ${DADATA_SECRET_KEY:test_key}
    url: https://cleaner.dadata.ru/api/v1/clean/address